### ISSUE TITLE
Adding Contextual Links after the end of the file for a specific topic

### ISSUE THREAD

**Issue by iSumitBanik** [CadenaDev/courses#28]
#### Overview

It has been noticed that all of the pages for specific topics are missing the contextual links for Next Topic to read next. I think it would be good if we can add the link to the next topic to read at the end of each file.

For Example, 

This is the content for lesson-blockchain-1 👇

> Now let’s pretend you took a picture of that Apple and promised your friend that the JPEG photo of the Apple represents the real apple you own and if they send you a dollar over PayPal you will give them the Apple.

**Read Next**: [Problems the Blockchain Aims to Solve](https://github.com/CadenaDev/courses/blob/main/blockchain-101/lesson-blockchain-2.md)

We can add this type of context links which will save the readers to directly visit the next topic.

**Comment by saeedjabbar** [comment]
@iSumitBanik thank you for this example. 

Are you also suggesting this in addition to the next and previous buttons at the bottom of the page? Thanks!

**Comment by iSumitBanik** [comment]
Oh, Okay. We already have the buttons.
Sorry, I missed that at my end.

Closing this issue.
Thanks.

**Comment by saeedjabbar** [comment]
Sure thing, were the buttons hard to see or blended in with the content too much?
Let us know and we can tweak them.
